'use client';

import React, { useEffect, useState } from 'react';
import { MapContainer, TileLayer, Marker, Popup, GeoJSON } from 'react-leaflet';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { supabase } from '@/lib/supabase';

interface MapPin {
  id: string;
  kk_name: string;
  rt_label: string;
  latitude: number;
  longitude: number;
  gps_accuracy: number;
  survey_status: 'completed' | 'verified' | 'locked' | 'rejected';
  problems: { category: string; description: string }[];
}

// Helper to create custom colored HTML markers with pulsing glow
const createHtmlIcon = (color: string, number: number) => {
  return L.divIcon({
    html: `
      <div class="relative flex items-center justify-center h-8 w-8 rounded-full border-2 border-white shadow-md transition hover:scale-110" style="background-color: ${color}">
        <span class="text-xxs font-bold text-white">${number}</span>
        <span class="absolute -top-1 -right-1 flex h-2.5 w-2.5">
          <span class="animate-ping absolute inline-flex h-full w-full rounded-full opacity-75" style="background-color: ${color}"></span>
          <span class="relative inline-flex rounded-full h-2.5 w-2.5" style="background-color: ${color}"></span>
        </span>
      </div>
    `,
    className: 'custom-leaflet-icon',
    iconSize: [32, 32],
    iconAnchor: [16, 16]
  });
};

// Default village boundary bounds for Cipeundeuy
const SUKAHAJI_BOUNDS: L.LatLngBoundsExpression = [
  [-6.850, 107.250],
  [-6.600, 107.500]
];

export default function MapComponent() {
  const [pins, setPins] = useState<MapPin[]>([]);
  const [rtFilter, setRtFilter] = useState('All');
  const [mapType, setMapType] = useState<'hybrid' | 'terrain' | 'osm'>('hybrid');
  const [colorMode, setColorMode] = useState<'problem' | 'status'>('problem');
  const [boundaryData, setBoundaryData] = useState<any>(null);

  // Fetch real GeoJSON administrative boundary generated by our Python GIS processor
  useEffect(() => {
    fetch('/data/sukahaji_boundary.json')
      .then((res) => res.json())
      .then((data) => setBoundaryData(data))
      .catch((err) => console.error('Error loading GeoJSON boundary:', err));
  }, []);

  // Fetch real household coordinates and problems list from Supabase
  useEffect(() => {
    const fetchRealMapData = async () => {
      try {
        const { data, error } = await supabase
          .from('household')
          .select(`
            id,
            kk_name,
            latitude,
            longitude,
            gps_accuracy,
            survey_status,
            rt (
              rt_number,
              rw (
                rw_number
              )
            ),
            survey (
              id,
              problem (
                category,
                description
              )
            )
          `)
          .is('deleted_at', null);

        if (error) throw error;

        if (data) {
          const loadedPins: MapPin[] = data.map((h: any) => {
            const rawProblems = h.survey?.[0]?.problem || [];
            const problems = rawProblems.map((p: any) => ({
              category: p.category,
              description: p.description
            }));

            const rtName = h.rt?.rt_number || 'RT 01';
            const rwName = h.rt?.rw?.rw_number || 'RW 01';

            return {
              id: h.id,
              kk_name: h.kk_name,
              rt_label: `${rtName} / ${rwName}`,
              latitude: Number(h.latitude),
              longitude: Number(h.longitude),
              gps_accuracy: Number(h.gps_accuracy || 0),
              survey_status: h.survey_status,
              problems
            };
          });

          // Merge local offline drafts
          const drafts = JSON.parse(localStorage.getItem('survey_drafts') || '[]');
          const draftPins = drafts.map((d: any) => ({
            id: d.client_uuid || `draft-map-${Math.random()}`,
            kk_name: d.kk_name,
            rt_label: d.rt_label,
            latitude: Number(d.latitude),
            longitude: Number(d.longitude),
            gps_accuracy: Number(d.gps_accuracy || 0),
            survey_status: 'completed',
            problems: d.problems || []
          }));

          const dbPinsFiltered = loadedPins.filter(p => !drafts.some((d: any) => d.client_uuid === p.id));
          setPins([...dbPinsFiltered, ...draftPins]);
        }
      } catch (err) {
        console.warn('Database connection empty or offline fallback active.');
        const drafts = JSON.parse(localStorage.getItem('survey_drafts') || '[]');
        const draftPins = drafts.map((d: any) => ({
          id: d.client_uuid || `draft-map-${Math.random()}`,
          kk_name: d.kk_name,
          rt_label: d.rt_label,
          latitude: Number(d.latitude),
          longitude: Number(d.longitude),
          gps_accuracy: Number(d.gps_accuracy || 0),
          survey_status: 'completed',
          problems: d.problems || []
        }));
        setPins(draftPins);
      }
    };

    fetchRealMapData();
  }, []);

  const filteredPins = rtFilter === 'All'
    ? pins
    : pins.filter(pin => pin.rt_label.includes(rtFilter));

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'locked': return '#22C55E'; // Green
      case 'verified': return '#3B82F6'; // Blue
      case 'completed': return '#EAB308'; // Yellow
      default: return '#EF4444'; // Red
    }
  };

  const getProblemColor = (problems: { category: string }[]) => {
    if (!problems || problems.length === 0) return '#94A3B8'; // Slate/Gray for no problems
    const firstCat = problems[0].category;
    switch (firstCat) {
      case 'Infrastruktur': return '#EF4444'; // Red
      case 'Kesehatan': return '#3B82F6'; // Blue
      case 'Ekonomi': return '#10B981'; // Green
      case 'Lingkungan': return '#F59E0B'; // Orange/Yellow
      case 'Pendidikan': return '#8B5CF6'; // Purple
      case 'Sosial-Budaya': return '#EC4899'; // Pink
      default: return '#6B7280'; // Gray
    }
  };

  return (
    <div className="space-y-4 font-sans text-slate-800">
      {/* Map Control Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 bg-white p-4 rounded-xl border border-slate-200 shadow-sm">
        <div className="flex flex-wrap items-center gap-4">
          <div>
            <span className="text-xs font-semibold text-slate-700 uppercase mr-2">Filter Wilayah:</span>
            <select
              value={rtFilter}
              onChange={(e) => setRtFilter(e.target.value)}
              className="rounded-lg border border-slate-300 bg-white text-slate-900 px-3 py-1.5 text-xs outline-none focus:border-indigo-500 transition"
            >
              <option value="All">Semua Wilayah RT/RW</option>
              <option value="RW 01">RW 01</option>
              <option value="RW 02">RW 02</option>
              <option value="RW 03">RW 03</option>
            </select>
          </div>
          
          <div>
            <span className="text-xs font-semibold text-slate-700 uppercase mr-2">Tipe Peta GIS:</span>
            <select
              value={mapType}
              onChange={(e) => setMapType(e.target.value as any)}
              className="rounded-lg border border-slate-300 bg-white text-slate-900 px-3 py-1.5 text-xs outline-none focus:border-indigo-500 transition font-bold"
            >
              <option value="hybrid">Satelit Hybrid (Google Satellite + Street labels)</option>
              <option value="terrain">Topografi Relief (Google Terrain)</option>
              <option value="osm">Peta Jalan Vector (OSM Standard)</option>
            </select>
          </div>

          {/* NEW: Toggle thematic coloring by problem category */}
          <div>
            <span className="text-xs font-semibold text-slate-700 uppercase mr-2">Pewarnaan Pin:</span>
            <select
              value={colorMode}
              onChange={(e) => setColorMode(e.target.value as any)}
              className="rounded-lg border border-slate-300 bg-white text-slate-900 px-3 py-1.5 text-xs outline-none focus:border-indigo-500 transition font-bold"
            >
              <option value="problem">Tematik Kategori Masalah (Rekomendasi)</option>
              <option value="status">Status Verifikasi Data</option>
            </select>
          </div>
        </div>
      </div>

      {/* Leaflet Map Container */}
      <div className="h-[480px] w-full rounded-2xl overflow-hidden border border-slate-200 shadow-sm relative z-10">
        <MapContainer
          center={[-6.7275, 107.3789]}
          zoom={15}
          minZoom={12}
          maxZoom={20}
          maxBounds={SUKAHAJI_BOUNDS}
          maxBoundsViscosity={0.6}
          style={{ height: '100%', width: '100%' }}
        >
          {mapType === 'osm' && (
            <TileLayer
              attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
              url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              maxZoom={20}
              maxNativeZoom={19}
            />
          )}
          {mapType === 'hybrid' && (
            <TileLayer
              attribution='&copy; Google Satellite Maps'
              url="https://mt1.google.com/vt/lyrs=y&x={x}&y={y}&z={z}"
              maxZoom={20}
              maxNativeZoom={18}
            />
          )}
          {mapType === 'terrain' && (
            <TileLayer
              attribution='&copy; Google Terrain Maps'
              url="https://mt1.google.com/vt/lyrs=p&x={x}&y={y}&z={z}"
              maxZoom={20}
              maxNativeZoom={15}
            />
          )}

          {/* DYNAMIC GEOJSON BOUNDARY OVERLAY:
              Loads the official boundary polygon of Desa Sukahaji Cipeundeuy
              fetched and generated by our Python script. */}
          {boundaryData && (
            <GeoJSON
              data={boundaryData}
              style={{
                fillColor: '#FF6B00',
                fillOpacity: 0.11,
                color: '#FF6B00',
                weight: 3,
                dashArray: '5, 10'
              }}
            />
          )}

          {filteredPins.map((pin) => {
            // Determine pin color based on selected mode
            const pinColor = colorMode === 'status'
              ? getStatusColor(pin.survey_status)
              : getProblemColor(pin.problems);

            return (
              <Marker
                key={pin.id}
                position={[pin.latitude, pin.longitude]}
                icon={createHtmlIcon(pinColor, pin.problems.length)}
              >
                <Popup>
                  <div className="p-1 font-sans text-slate-800 max-w-xs">
                    <h4 className="font-bold text-sm text-slate-850">{pin.kk_name}</h4>
                    <p className="text-[10px] text-slate-500 mt-0.5">{pin.rt_label}</p>
                    
                    <div className="mt-2 space-y-1.5 text-xxs border-t border-slate-100 pt-1.5">
                      <div className="flex justify-between gap-4">
                        <span className="text-slate-400">Akurasi GPS:</span>
                        <span className="font-semibold text-slate-700">{pin.gps_accuracy.toFixed(1)}m</span>
                      </div>
                      <div className="flex justify-between gap-4">
                        <span className="text-slate-400">Status Data:</span>
                        <span className="font-bold uppercase text-slate-700">{pin.survey_status}</span>
                      </div>
                      
                      {/* Household Problems Popup List */}
                      <div className="mt-2 pt-2 border-t border-slate-100">
                        <span className="font-bold text-slate-700 block mb-1 text-[10px]">Identifikasi Masalah ({pin.problems.length}):</span>
                        {pin.problems.length > 0 ? (
                          <ul className="space-y-1 text-slate-600 max-h-24 overflow-y-auto pl-1 pr-1">
                            {pin.problems.map((p, idx) => (
                              <li key={idx} className="bg-red-50/50 p-1 rounded border border-red-100/50">
                                <span className="font-bold text-red-700 text-[9px] uppercase">[{p.category}]</span>
                                <p className="text-[10px] text-slate-750 font-medium mt-0.5 leading-tight">{p.description}</p>
                              </li>
                            ))}
                          </ul>
                        ) : (
                          <span className="text-slate-400 italic">Tidak ada keluhan terdaftar.</span>
                        )}
                      </div>
                    </div>
                  </div>
                </Popup>
              </Marker>
            );
          })}
        </MapContainer>
      </div>

      {/* NEW: Dynamic Map Legend Card overlaying below the map */}
      <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-sm space-y-2">
        <span className="text-xxs font-extrabold text-slate-400 uppercase tracking-wider block">Legenda Peta Tematik</span>
        <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-7 gap-3 text-xxs font-bold text-slate-700">
          {colorMode === 'status' ? (
            <>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#22C55E]" /> Terkunci</span>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#3B82F6]" /> Terverifikasi</span>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#EAB308]" /> Dikirim (Draft)</span>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#EF4444]" /> Perlu Perbaikan</span>
            </>
          ) : (
            <>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#EF4444]" /> Infrastruktur</span>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#3B82F6]" /> Kesehatan</span>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#10B981]" /> Ekonomi</span>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#F59E0B]" /> Lingkungan</span>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#8B5CF6]" /> Pendidikan</span>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#EC4899]" /> Sosial-Budaya</span>
              <span className="flex items-center gap-1.5"><span className="h-3 w-3 rounded-full bg-[#94A3B8]" /> Tidak Ada Masalah</span>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
